name: cli_tools_manager
description: A Dart-based task runner and tooling suite for managing CLI tools documentation
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  collection: ^1.18.0
  yaml: ^3.1.2
  http: ^1.2.0
  crypto: ^3.0.3
  intl: ^0.19.0
  ansicolor: ^2.0.2
  markdown: ^7.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  cli_tools: main