name: Validate Documentation

on:
  push:
    branches: [main, develop]
    paths:
      - "**.md"
      - "CLAUDE.md.tpl"
      - "site/data/tools.json"
      - "scripts/*.sh"
      - ".github/workflows/validate_docs.yml"
      - ".markdownlint.json"
  pull_request:
    branches: [main]
    paths:
      - "**.md"
      - "CLAUDE.md.tpl"
      - "site/data/tools.json"
      - "scripts/*.sh"
      - ".github/workflows/validate_docs.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need full history for git info

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          # Install markdown linter
          npm install -g markdownlint-cli2

          # Install JSON validator
          pip install jsonschema

          # Make scripts executable
          chmod +x scripts/*.sh

      # - name: Validate Markdown formatting
      #   run: |
      #     echo "Validating Markdown files..."
      #     markdownlint-cli2 "**/*.md" || true  # Warning only, don't fail

      - name: Validate tools.json
        run: |
          echo "Validating tools.json structure..."
          python3 -c "
          import json
          import sys

          try:
              with open('site/data/tools.json', 'r') as f:
                  data = json.load(f)
                  
              # Check required fields
              assert 'tools' in data, 'Missing tools array'
              assert isinstance(data['tools'], list), 'Tools must be an array'
              
              # Validate each tool
              for tool in data['tools']:
                  assert 'name' in tool, f'Tool missing name: {tool}'
                  assert 'category' in tool, f'Tool {tool.get(\"name\", \"unknown\")} missing category'
                  assert 'description' in tool, f'Tool {tool.get(\"name\", \"unknown\")} missing description'
              
              print(f'✅ Validated {len(data[\"tools\"])} tools')
              
          except Exception as e:
              print(f'❌ JSON validation failed: {e}')
              sys.exit(1)
          "

      # - name: Check CLAUDE.md is up to date
      #   run: |
      #     echo "Checking if CLAUDE.md needs regeneration..."

      #     # Generate fresh CLAUDE.md
      #     ./scripts/build_claude_md.sh

      #     # Check if there are differences
      #     if git diff --exit-code CLAUDE.md; then
      #       echo "✅ CLAUDE.md is up to date"
      #     else
      #       echo "❌ CLAUDE.md is out of date. Please run: scripts/build_claude_md.sh"
      #       echo "Differences found:"
      #       git diff CLAUDE.md
      #       exit 1
      #     fi

      - name: Verify tool counts match
        run: |
          echo "Verifying tool counts..."

          # Count tools in tools.json
          JSON_COUNT=$(python3 -c "
          import json
          with open('site/data/tools.json', 'r') as f:
              data = json.load(f)
              print(len(data['tools']))
          ")

          # Count tools mentioned in CLAUDE.md
          CLAUDE_COUNT=$(grep -oE '\*\*[0-9]+ CLI tools\*\*' CLAUDE.md | head -1 | grep -oE '[0-9]+')

          if [ "$JSON_COUNT" == "$CLAUDE_COUNT" ]; then
            echo "✅ Tool counts match: $JSON_COUNT"
          else
            echo "❌ Tool count mismatch!"
            echo "   tools.json: $JSON_COUNT"
            echo "   CLAUDE.md: $CLAUDE_COUNT"
            exit 1
          fi

      - name: Check for broken internal links
        run: |
          echo "Checking for broken internal links..."

          # Find all markdown links to local files
          python3 -c "
          import re
          import sys
          import glob
          from pathlib import Path

          broken_links = []

          for md_file in glob.glob('**/*.md', recursive=True):
              if 'node_modules' in md_file:
                  continue
                  
              md_path = Path(md_file)
              with open(md_path, 'r') as f:
                  content = f.read()
              
              # Remove code blocks to avoid false positives
              # Remove fenced code blocks (```...```)
              content = re.sub(r'```[\s\S]*?```', '', content, flags=re.MULTILINE)
              # Remove indented code blocks (4+ spaces at start of line)
              content = re.sub(r'^[ ]{4,}.*$', '', content, flags=re.MULTILINE)
                  
              # Find markdown links, excluding image links
              # Pattern matches [text](link) but not ![alt](image)
              links = re.findall(r'(?<!\!)\[([^\]]+)\]\(([^)]+)\)', content)
              
              for text, link in links:
                  # Skip external links
                  if link.startswith(('http://', 'https://', 'ftp://', 'mailto:', 'tel:', 'file://', 'data:', 'javascript:')):
                      continue
                      
                  # Skip anchors
                  if link.startswith('#'):
                      continue
                  
                  # Skip if link contains shell variables or special patterns
                  # These are likely code examples, not actual file links
                  if any(pattern in link for pattern in [
                      '$', '{', '}', '*', '|',  # Shell/regex special chars
                      'bold', 'green', 'red', 'style',  # Starship config values
                      '^', '[', ']' # Regex patterns
                  ]):
                      continue
                  
                  # Skip if link doesn't end with .md or doesn't contain a dot (likely not a file)
                  # Allow links to directories without extension
                  if not ('.' in link or link.endswith('/')):
                      # Could be a directory, check if it exists
                      pass
                  
                  # Clean up the link path
                  link_path = link.split('#')[0]  # Remove anchor if present
                  
                  # Skip empty paths
                  if not link_path:
                      continue
                      
                  # Check if file exists
                  if link_path.startswith('/'):
                      # Absolute path from repo root
                      check_path = Path(link_path[1:])
                  elif link_path.startswith('./'):
                      # Relative path from current markdown file
                      check_path = md_path.parent / link_path[2:]
                  elif link_path.startswith('../'):
                      # Relative path going up directories
                      check_path = md_path.parent / link_path
                  else:
                      # Relative path from current markdown file
                      check_path = md_path.parent / link_path
                  
                  # Resolve to absolute path and check existence
                  try:
                      check_path = check_path.resolve()
                      if not check_path.exists():
                          # Only report as broken if it looks like a file link
                          if '.md' in link or '.txt' in link or '.sh' in link or '.json' in link:
                              broken_links.append(f'{md_file}: [{text}]({link})')
                  except Exception:
                      # Path resolution failed, skip
                      pass

          if broken_links:
              print('❌ Found broken internal links:')
              for link in broken_links:
                  print(f'   {link}')
              sys.exit(1)
          else:
              print('✅ No broken internal links found')
          "

      - name: Validate script executability
        run: |
          echo "Checking script permissions..."

          for script in scripts/*.sh; do
            if [ -f "$script" ]; then
              if [ -x "$script" ]; then
                echo "✅ $script is executable"
              else
                echo "❌ $script is not executable"
                echo "   Run: chmod +x $script"
                exit 1
              fi
            fi
          done

      - name: Check documentation completeness
        run: |
          echo "Checking documentation completeness..."

          # Check required files exist
          REQUIRED_FILES=(
            "README.md"
            "TOOLS.md"
            "CLAUDE.md"
            "CLAUDE.md.tpl"
            "docs/templates/simple_query.md"
            "docs/templates/complex_pipeline.md"
            "docs/snippets/lookup_patterns.md"
            "docs/snippets/debugging_checklist.md"
            "docs/safety/comprehensive_safety_guide.md"
          )

          for file in "${REQUIRED_FILES[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ Found: $file"
            else
              echo "❌ Missing: $file"
              exit 1
            fi
          done

      - name: Summary
        if: always()
        run: |
          echo "======================================="
          echo "Documentation Validation Complete"
          echo "======================================="
          echo ""
          echo "Checks performed:"
          echo "- Markdown formatting"
          echo "- JSON structure validation"
          echo "- CLAUDE.md freshness"
          echo "- Tool count consistency"
          echo "- Internal link validation"
          echo "- Script permissions"
          echo "- Documentation completeness"
